app = 'studio-matic-s4l-db'
primary_region = 'fra'

[build]
image = 'mysql:9.5.0'

[processes]
app = '--datadir /data/mysql'

[[mounts]]
source = 'mysqldata'
destination = '/data'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
